version: "3.9"
services:
  mysqldb:
    image: "mysql:8.0"
    container_name: mysql8
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
      - MYSQL_USER=$MYSQLDB_USER
      - MYSQL_PASSWORD=$MYSQLDB_PASSWORD
    ports:
      - "3307:3306"
    volumes:
      - db:/var/lib/mysql
    networks:
      - backend

  app:
    build: .
    restart: on-failure
    env_file: ./.env
    ports:
      - "80:8080"
    depends_on:
      - mysqldb
    container_name: mbti-test-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/$MYSQLDB_DATABASE?serverTimezone=UTC&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: $MYSQLDB_USER
      SPRING_DATASOURCE_PASSWORD: $MYSQLDB_PASSWORD
    networks:
      - backend

volumes:
  db:
networks:
  backend: