# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: rsync over ssh
        run: ./deploy.sh
#      - name: executing ssh commands using ssh key
#        uses: appleboy/ssh-action@v0.1.4
#        with:
#          host: ${{ secrets.HOST_NAME}}
#          username: ${{ secrets.USER_NAME }}
#          key: ${{ secrets.KEY }}
#          script: whoami
#          script: |
#            cd mbti-test-api/
#            docker-compose down
#            git checkout main
#            git fetch --all
#            git reset --hard origin/main
#            git pull origin main
#            chmod +x ./deploy.sh
#            ./deploy.sh

      - name: Slack Notify
        uses: rtCamp/action-slack-notify@v2.2.0
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}